### ISSUE TITLE
Error trying to run the demo

### ISSUE THREAD

**Issue by rxaviers** [devangnegandhi/globalize-express#1]
Hi @devangnegandhi,

I've tried to run the demo with

    cd example
    npm install
    npm start

I get a Globalize error (suggesting data hasn't been loaded):

    Error: E_MISSING_CLDR: Missing required CLDR content `supplemental/plurals-type-cardinal/fr`.
       at createError (/tmp/globalize-express/example/node_modules/globalize-express/node_modules/globalize/dist/globalize.js:105:10)
       at validate (/tmp/globalize-express/example/node_modules/globalize-express/node_modules/globalize/dist/globalize.js:158:9)
       at EventEmitter.validateCldr (/tmp/globalize-express/example/node_modules/globalize-express/node_modules/globalize/dist/globalize.js:180:2)
       at EventEmitter.emitEvent (/tmp/globalize-express/example/node_modules/globalize-express/node_modules/globalize/node_modules/cldrjs/dist/cldr/event.js:416:35)
       at EventEmitter.aliasClosure [as trigger] (/tmp/globalize-express/example/node_modules/globalize-express/node_modules/globalize/node_modules/cldrjs/dist/cldr/event.js:88:22)
       at Cldr.get (/tmp/globalize-express/example/node_modules/globalize-express/node_modules/globalize/node_modules/cldrjs/dist/cldr/event.js:572:12)
       at null.supplemental (/tmp/globalize-express/example/node_modules/globalize-express/node_modules/globalize/node_modules/cldrjs/dist/cldr/supplemental.js:42:17)
       at Globalize.pluralGenerator.Globalize.pluralGenerator (/tmp/globalize-express/example/node_modules/globalize-express/node_modules/globalize/dist/globalize/plural.js:350:7)
       at Globalize.messageFormatter.Globalize.messageFormatter (/tmp/globalize-express/example/node_modules/globalize-express/node_modules/globalize/dist/globalize/message.js:2044:8)
       at Globalize.formatMessage.Globalize.formatMessage (/tmp/globalize-express/example/node_modules/globalize-express/node_modules/globalize/dist/globalize/message.js:2067:14)

**Comment by devangnegandhi** [comment]
@rxaviers - That's weird!! I ran these exact steps on 2 laptops - one running mac and another running linux, and it seems to work fine for me. Also, I have automated browser tests for the globalize-express package that run these exact steps on the CI (codeship.com) for testing. I am not sure why it would not work for you. Could you try this again?

**Comment by rxaviers** [comment]
I get the above error when I try to open `http://0.0.0.0:3000/` on a browser after having created a brand new clone of this repo and executed the commands above. Tested on linux, node v0.10.40 and v0.12.0, npm ls result at https://gist.github.com/rxaviers/9f99cbe96a4eea1f0343.

Please, just let me know if I can provide you any additional details.

**Comment by rxaviers** [comment]
I have added the below to inspect which CLDR data you're loading

```diff
--- a/src/globalize-express.js
+++ b/src/globalize-express.js
@@ -97,6 +97,7 @@ function loadLocaleData (dataList) {
        var i;
 
        for (i = 0; i < dataList.length; i++) {
+               console.log('globalize.load', dataList[i])
                globalize.load(require(dataList[i]));
        }
 }
```
I got this:

```
globalize.load cldr-data/supplemental/likelySubtags
globalize.load cldr-data/supplemental/numberingSystems.json
globalize.load cldr-data/supplemental/currencyData.json
globalize.load cldr-data/supplemental/timeData.json
globalize.load cldr-data/supplemental/weekData.json
globalize.load cldr-data/main/en/numbers.json
globalize.load cldr-data/main/en/ca-gregorian.json
globalize.load cldr-data/main/en/timeZoneNames.json
globalize.load cldr-data/main/en/currencies.json
globalize.load cldr-data/main/fr/numbers.json
globalize.load cldr-data/main/fr/ca-gregorian.json
globalize.load cldr-data/main/fr/timeZoneNames.json
globalize.load cldr-data/main/fr/currencies.json
globalize.load cldr-data/main/de/numbers.json
globalize.load cldr-data/main/de/ca-gregorian.json
globalize.load cldr-data/main/de/timeZoneNames.json
globalize.load cldr-data/main/de/currencies.json
```

It misses loading `cldr/supplemental/plurals.json`.

**Comment by devangnegandhi** [comment]
@rxaviers I have made the changes. Can you please check if it works for you now?

**Comment by rxaviers** [comment]
Hi @devangnegandhi, sorry for the long delay, it works just fine to me now. Thx
